package org.mitre.openid.connect.sys.model;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;

import org.mitre.openid.connect.model.IAddress;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="SYS_M_ADDRESS"
)
public class Address  implements IAddress, java.io.Serializable {


     private Long idAddress;
     private County county;
     private String housingNo;
     private String streetAddress1;
     private String streetAddress2;
     private String zipcode;
     private String lat;
     private String lng;
     private String description;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<AddressMapPhone> addressMapPhones = new ArrayList<AddressMapPhone>(0);
     private List<UserMapAddress> userMapAddresses = new ArrayList<UserMapAddress>(0);

    public Address() {
    }

    public Address(County county, String housingNo, String streetAddress1, String streetAddress2, String zipcode, String lat, String lng, String description, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<AddressMapPhone> addressMapPhones, List<UserMapAddress> userMapAddresses) {
       this.county = county;
       this.housingNo = housingNo;
       this.streetAddress1 = streetAddress1;
       this.streetAddress2 = streetAddress2;
       this.zipcode = zipcode;
       this.lat = lat;
       this.lng = lng;
       this.description = description;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.addressMapPhones = addressMapPhones;
       this.userMapAddresses = userMapAddresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_ADDRESS", unique=true, nullable=false)
    public Long getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Long idAddress) {
        this.idAddress = idAddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_COUNTRY", referencedColumnName="ID_COUNTRY"), 
        @JoinColumn(name="ID_PROVINCE", referencedColumnName="ID_PROVINCE"), 
        @JoinColumn(name="ID_CITY", referencedColumnName="ID_CITY"), 
        @JoinColumn(name="ID_COUNTY", referencedColumnName="ID_COUNTY") } )
    public County getCounty() {
        return this.county;
    }
    
    public void setCounty(County county) {
        this.county = county;
    }

    
    @Column(name="HOUSING_NO")
    public String getHousingNo() {
        return this.housingNo;
    }
    
    public void setHousingNo(String housingNo) {
        this.housingNo = housingNo;
    }

    
    @Column(name="STREET_ADDRESS1")
    public String getStreetAddress1() {
        return this.streetAddress1;
    }
    
    public void setStreetAddress1(String streetAddress1) {
        this.streetAddress1 = streetAddress1;
    }

    
    @Column(name="STREET_ADDRESS2")
    public String getStreetAddress2() {
        return this.streetAddress2;
    }
    
    public void setStreetAddress2(String streetAddress2) {
        this.streetAddress2 = streetAddress2;
    }

    
    @Column(name="ZIPCODE")
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    
    @Column(name="LAT")
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }

    
    @Column(name="LNG")
    public String getLng() {
        return this.lng;
    }
    
    public void setLng(String lng) {
        this.lng = lng;
    }

    
    @Column(name="DESCRIPTION", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public List<AddressMapPhone> getAddressMapPhones() {
        return this.addressMapPhones;
    }
    
    public void setAddressMapPhones(List<AddressMapPhone> addressMapPhones) {
        this.addressMapPhones = addressMapPhones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public List<UserMapAddress> getUserMapAddresses() {
        return this.userMapAddresses;
    }
    
    public void setUserMapAddresses(List<UserMapAddress> userMapAddresses) {
        this.userMapAddresses = userMapAddresses;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idAddress").append("='").append(getIdAddress()).append("' ");			
      buffer.append("county").append("='").append(getCounty()).append("' ");			
      buffer.append("housingNo").append("='").append(getHousingNo()).append("' ");			
      buffer.append("streetAddress1").append("='").append(getStreetAddress1()).append("' ");			
      buffer.append("streetAddress2").append("='").append(getStreetAddress2()).append("' ");			
      buffer.append("zipcode").append("='").append(getZipcode()).append("' ");			
      buffer.append("lat").append("='").append(getLat()).append("' ");			
      buffer.append("lng").append("='").append(getLng()).append("' ");			
      buffer.append("description").append("='").append(getDescription()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Address) ) return false;
		 Address castOther = ( Address ) other; 
         
		 return ( (this.getIdAddress()==castOther.getIdAddress()) || ( this.getIdAddress()!=null && castOther.getIdAddress()!=null && this.getIdAddress().equals(castOther.getIdAddress()) ) )
 && ( (this.getCounty()==castOther.getCounty()) || ( this.getCounty()!=null && castOther.getCounty()!=null && this.getCounty().equals(castOther.getCounty()) ) )
 && ( (this.getHousingNo()==castOther.getHousingNo()) || ( this.getHousingNo()!=null && castOther.getHousingNo()!=null && this.getHousingNo().equals(castOther.getHousingNo()) ) )
 && ( (this.getStreetAddress1()==castOther.getStreetAddress1()) || ( this.getStreetAddress1()!=null && castOther.getStreetAddress1()!=null && this.getStreetAddress1().equals(castOther.getStreetAddress1()) ) )
 && ( (this.getStreetAddress2()==castOther.getStreetAddress2()) || ( this.getStreetAddress2()!=null && castOther.getStreetAddress2()!=null && this.getStreetAddress2().equals(castOther.getStreetAddress2()) ) )
 && ( (this.getZipcode()==castOther.getZipcode()) || ( this.getZipcode()!=null && castOther.getZipcode()!=null && this.getZipcode().equals(castOther.getZipcode()) ) )
 && ( (this.getLat()==castOther.getLat()) || ( this.getLat()!=null && castOther.getLat()!=null && this.getLat().equals(castOther.getLat()) ) )
 && ( (this.getLng()==castOther.getLng()) || ( this.getLng()!=null && castOther.getLng()!=null && this.getLng().equals(castOther.getLng()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdAddress() == null ? 0 : this.getIdAddress().hashCode() );
         result = 37 * result + ( getCounty() == null ? 0 : this.getCounty().hashCode() );
         result = 37 * result + ( getHousingNo() == null ? 0 : this.getHousingNo().hashCode() );
         result = 37 * result + ( getStreetAddress1() == null ? 0 : this.getStreetAddress1().hashCode() );
         result = 37 * result + ( getStreetAddress2() == null ? 0 : this.getStreetAddress2().hashCode() );
         result = 37 * result + ( getZipcode() == null ? 0 : this.getZipcode().hashCode() );
         result = 37 * result + ( getLat() == null ? 0 : this.getLat().hashCode() );
         result = 37 * result + ( getLng() == null ? 0 : this.getLng().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         
         
         return result;
   }
   @Transient
@Override
public Long getId() {
	return idAddress;
}
   @Transient
@Override
public String getFormatted() {
	// TODO Auto-generated method stub
	return null;
}

@Override
public void setFormatted(String formatted) {
	// TODO Auto-generated method stub
	
}
@Transient
@Override
public String getStreetAddress() {
	return streetAddress1+streetAddress2;
}

@Override
public void setStreetAddress(String streetAddress) {
	// TODO Auto-generated method stub
	
}
@Transient
@Override
public String getLocality() {
	// TODO Auto-generated method stub
	return null;
}

@Override
public void setLocality(String locality) {
	// TODO Auto-generated method stub
	
}
@Transient
@Override
public String getRegion() {
	// TODO Auto-generated method stub
	return null;
}

@Override
public void setRegion(String region) {
	// TODO Auto-generated method stub
	
}
@Transient
@Override
public String getPostalCode() {
	return zipcode;
}

@Override
public void setPostalCode(String postalCode) {
	// TODO Auto-generated method stub
	
}
@Transient
@Override
public String getCountry() {
	if(county!=null&&county.getCity()!=null&&county.getCity().getProvince()!=null&&county.getCity().getProvince().getCountry()!=null){
		return county.getCity().getProvince().getCountry().getName();
	}
	
	return null;
}

@Override
public void setCountry(String country) {
	// TODO Auto-generated method stub
	
}   


}


