package org.mitre.openid.connect.sys.model;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CountyId generated by hbm2java
 */
@Embeddable
public class CountyId  implements java.io.Serializable {


     private Long idCountry;
     private Long idProvince;
     private Long idCity;
     private Long idCounty;

    public CountyId() {
    }

    public CountyId(Long idCountry, Long idProvince, Long idCity, Long idCounty) {
       this.idCountry = idCountry;
       this.idProvince = idProvince;
       this.idCity = idCity;
       this.idCounty = idCounty;
    }
   


    @Column(name="ID_COUNTRY", nullable=false)
    public Long getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(Long idCountry) {
        this.idCountry = idCountry;
    }


    @Column(name="ID_PROVINCE", nullable=false)
    public Long getIdProvince() {
        return this.idProvince;
    }
    
    public void setIdProvince(Long idProvince) {
        this.idProvince = idProvince;
    }


    @Column(name="ID_CITY", nullable=false)
    public Long getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(Long idCity) {
        this.idCity = idCity;
    }


    @Column(name="ID_COUNTY", nullable=false)
    public Long getIdCounty() {
        return this.idCounty;
    }
    
    public void setIdCounty(Long idCounty) {
        this.idCounty = idCounty;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountyId) ) return false;
		 CountyId castOther = ( CountyId ) other; 
         
		 return ( (this.getIdCountry()==castOther.getIdCountry()) || ( this.getIdCountry()!=null && castOther.getIdCountry()!=null && this.getIdCountry().equals(castOther.getIdCountry()) ) )
 && ( (this.getIdProvince()==castOther.getIdProvince()) || ( this.getIdProvince()!=null && castOther.getIdProvince()!=null && this.getIdProvince().equals(castOther.getIdProvince()) ) )
 && ( (this.getIdCity()==castOther.getIdCity()) || ( this.getIdCity()!=null && castOther.getIdCity()!=null && this.getIdCity().equals(castOther.getIdCity()) ) )
 && ( (this.getIdCounty()==castOther.getIdCounty()) || ( this.getIdCounty()!=null && castOther.getIdCounty()!=null && this.getIdCounty().equals(castOther.getIdCounty()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCountry() == null ? 0 : this.getIdCountry().hashCode() );
         result = 37 * result + ( getIdProvince() == null ? 0 : this.getIdProvince().hashCode() );
         result = 37 * result + ( getIdCity() == null ? 0 : this.getIdCity().hashCode() );
         result = 37 * result + ( getIdCounty() == null ? 0 : this.getIdCounty().hashCode() );
         return result;
   }   


}


