package org.mitre.openid.connect.sys.model;



import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * CountryMapPhoneCode generated by hbm2java
 */
@Entity
@Table(name="SYS_M_COUNTRY_MAP_PHONE_CODE"
)
public class CountryMapPhoneCode  implements java.io.Serializable {


     private Long idCountryMapPhoneCode;
     private Country country;
     private PhoneCode phoneCode;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public CountryMapPhoneCode() {
    }

	
    public CountryMapPhoneCode(Date createDate) {
        this.createDate = createDate;
    }
    public CountryMapPhoneCode(Country country, PhoneCode phoneCode, String status, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.country = country;
       this.phoneCode = phoneCode;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_COUNTRY_MAP_PHONE_CODE", unique=true, nullable=false)
    public Long getIdCountryMapPhoneCode() {
        return this.idCountryMapPhoneCode;
    }
    
    public void setIdCountryMapPhoneCode(Long idCountryMapPhoneCode) {
        this.idCountryMapPhoneCode = idCountryMapPhoneCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COUNTRY")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PHONE_CODE")
    public PhoneCode getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(PhoneCode phoneCode) {
        this.phoneCode = phoneCode;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idCountryMapPhoneCode").append("='").append(getIdCountryMapPhoneCode()).append("' ");			
      buffer.append("country").append("='").append(getCountry()).append("' ");			
      buffer.append("phoneCode").append("='").append(getPhoneCode()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountryMapPhoneCode) ) return false;
		 CountryMapPhoneCode castOther = ( CountryMapPhoneCode ) other; 
         
		 return ( (this.getIdCountryMapPhoneCode()==castOther.getIdCountryMapPhoneCode()) || ( this.getIdCountryMapPhoneCode()!=null && castOther.getIdCountryMapPhoneCode()!=null && this.getIdCountryMapPhoneCode().equals(castOther.getIdCountryMapPhoneCode()) ) )
 && ( (this.getCountry()==castOther.getCountry()) || ( this.getCountry()!=null && castOther.getCountry()!=null && this.getCountry().equals(castOther.getCountry()) ) )
 && ( (this.getPhoneCode()==castOther.getPhoneCode()) || ( this.getPhoneCode()!=null && castOther.getPhoneCode()!=null && this.getPhoneCode().equals(castOther.getPhoneCode()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCountryMapPhoneCode() == null ? 0 : this.getIdCountryMapPhoneCode().hashCode() );
         result = 37 * result + ( getCountry() == null ? 0 : this.getCountry().hashCode() );
         result = 37 * result + ( getPhoneCode() == null ? 0 : this.getPhoneCode().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         return result;
   }   


}


