package org.mitre.openid.connect.sys.model;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="SYS_M_COUNTRY"
)
public class Country  implements java.io.Serializable {


     private Long idCountry;
     private String name;
     private String code2;
     private String code3;
     private Long idRegion;
     private Long idLanguage;
     private Long idCurrency;
     private String phoneCode;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<Province> provinces = new ArrayList<Province>(0);
     private List<CountryMapPhoneCode> countryMapPhoneCodes = new ArrayList<CountryMapPhoneCode>(0);

    public Country() {
    }

    public Country(String name, String code2, String code3, Long idRegion, Long idLanguage, Long idCurrency, String phoneCode, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<Province> provinces, List<CountryMapPhoneCode> countryMapPhoneCodes) {
       this.name = name;
       this.code2 = code2;
       this.code3 = code3;
       this.idRegion = idRegion;
       this.idLanguage = idLanguage;
       this.idCurrency = idCurrency;
       this.phoneCode = phoneCode;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.provinces = provinces;
       this.countryMapPhoneCodes = countryMapPhoneCodes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_COUNTRY", unique=true, nullable=false)
    public Long getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(Long idCountry) {
        this.idCountry = idCountry;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="CODE2", length=2)
    public String getCode2() {
        return this.code2;
    }
    
    public void setCode2(String code2) {
        this.code2 = code2;
    }

    
    @Column(name="CODE3", length=3)
    public String getCode3() {
        return this.code3;
    }
    
    public void setCode3(String code3) {
        this.code3 = code3;
    }

    
    @Column(name="ID_REGION")
    public Long getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(Long idRegion) {
        this.idRegion = idRegion;
    }

    
    @Column(name="ID_LANGUAGE")
    public Long getIdLanguage() {
        return this.idLanguage;
    }
    
    public void setIdLanguage(Long idLanguage) {
        this.idLanguage = idLanguage;
    }

    
    @Column(name="ID_CURRENCY")
    public Long getIdCurrency() {
        return this.idCurrency;
    }
    
    public void setIdCurrency(Long idCurrency) {
        this.idCurrency = idCurrency;
    }

    
    @Column(name="PHONE_CODE", length=10)
    public String getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public List<Province> getProvinces() {
        return this.provinces;
    }
    
    public void setProvinces(List<Province> provinces) {
        this.provinces = provinces;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public List<CountryMapPhoneCode> getCountryMapPhoneCodes() {
        return this.countryMapPhoneCodes;
    }
    
    public void setCountryMapPhoneCodes(List<CountryMapPhoneCode> countryMapPhoneCodes) {
        this.countryMapPhoneCodes = countryMapPhoneCodes;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idCountry").append("='").append(getIdCountry()).append("' ");			
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("code2").append("='").append(getCode2()).append("' ");			
      buffer.append("code3").append("='").append(getCode3()).append("' ");			
      buffer.append("idRegion").append("='").append(getIdRegion()).append("' ");			
      buffer.append("idLanguage").append("='").append(getIdLanguage()).append("' ");			
      buffer.append("idCurrency").append("='").append(getIdCurrency()).append("' ");			
      buffer.append("phoneCode").append("='").append(getPhoneCode()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Country) ) return false;
		 Country castOther = ( Country ) other; 
         
		 return ( (this.getIdCountry()==castOther.getIdCountry()) || ( this.getIdCountry()!=null && castOther.getIdCountry()!=null && this.getIdCountry().equals(castOther.getIdCountry()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getCode2()==castOther.getCode2()) || ( this.getCode2()!=null && castOther.getCode2()!=null && this.getCode2().equals(castOther.getCode2()) ) )
 && ( (this.getCode3()==castOther.getCode3()) || ( this.getCode3()!=null && castOther.getCode3()!=null && this.getCode3().equals(castOther.getCode3()) ) )
 && ( (this.getIdRegion()==castOther.getIdRegion()) || ( this.getIdRegion()!=null && castOther.getIdRegion()!=null && this.getIdRegion().equals(castOther.getIdRegion()) ) )
 && ( (this.getIdLanguage()==castOther.getIdLanguage()) || ( this.getIdLanguage()!=null && castOther.getIdLanguage()!=null && this.getIdLanguage().equals(castOther.getIdLanguage()) ) )
 && ( (this.getIdCurrency()==castOther.getIdCurrency()) || ( this.getIdCurrency()!=null && castOther.getIdCurrency()!=null && this.getIdCurrency().equals(castOther.getIdCurrency()) ) )
 && ( (this.getPhoneCode()==castOther.getPhoneCode()) || ( this.getPhoneCode()!=null && castOther.getPhoneCode()!=null && this.getPhoneCode().equals(castOther.getPhoneCode()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCountry() == null ? 0 : this.getIdCountry().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getCode2() == null ? 0 : this.getCode2().hashCode() );
         result = 37 * result + ( getCode3() == null ? 0 : this.getCode3().hashCode() );
         result = 37 * result + ( getIdRegion() == null ? 0 : this.getIdRegion().hashCode() );
         result = 37 * result + ( getIdLanguage() == null ? 0 : this.getIdLanguage().hashCode() );
         result = 37 * result + ( getIdCurrency() == null ? 0 : this.getIdCurrency().hashCode() );
         result = 37 * result + ( getPhoneCode() == null ? 0 : this.getPhoneCode().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         
         
         return result;
   }   


}


