package org.mitre.openid.connect.sys.model;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * PhoneCode generated by hbm2java
 */
@Entity
@Table(name="SYS_M_PHONE_CODE"
)
public class PhoneCode  implements java.io.Serializable {


     private Long idPhoneCode;
     private String phoneCode;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<CountryMapPhoneCode> countryMapPhoneCodes = new ArrayList<CountryMapPhoneCode>(0);
     private List<Phone> phones = new ArrayList<Phone>(0);

    public PhoneCode() {
    }

	
    public PhoneCode(Date createDate) {
        this.createDate = createDate;
    }
    public PhoneCode(String phoneCode, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<CountryMapPhoneCode> countryMapPhoneCodes, List<Phone> phones) {
       this.phoneCode = phoneCode;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.countryMapPhoneCodes = countryMapPhoneCodes;
       this.phones = phones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PHONE_CODE", unique=true, nullable=false)
    public Long getIdPhoneCode() {
        return this.idPhoneCode;
    }
    
    public void setIdPhoneCode(Long idPhoneCode) {
        this.idPhoneCode = idPhoneCode;
    }

    
    @Column(name="PHONE_CODE", length=10)
    public String getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phoneCode")
    public List<CountryMapPhoneCode> getCountryMapPhoneCodes() {
        return this.countryMapPhoneCodes;
    }
    
    public void setCountryMapPhoneCodes(List<CountryMapPhoneCode> countryMapPhoneCodes) {
        this.countryMapPhoneCodes = countryMapPhoneCodes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phoneCode")
    public List<Phone> getPhones() {
        return this.phones;
    }
    
    public void setPhones(List<Phone> phones) {
        this.phones = phones;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idPhoneCode").append("='").append(getIdPhoneCode()).append("' ");			
      buffer.append("phoneCode").append("='").append(getPhoneCode()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhoneCode) ) return false;
		 PhoneCode castOther = ( PhoneCode ) other; 
         
		 return ( (this.getIdPhoneCode()==castOther.getIdPhoneCode()) || ( this.getIdPhoneCode()!=null && castOther.getIdPhoneCode()!=null && this.getIdPhoneCode().equals(castOther.getIdPhoneCode()) ) )
 && ( (this.getPhoneCode()==castOther.getPhoneCode()) || ( this.getPhoneCode()!=null && castOther.getPhoneCode()!=null && this.getPhoneCode().equals(castOther.getPhoneCode()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPhoneCode() == null ? 0 : this.getIdPhoneCode().hashCode() );
         result = 37 * result + ( getPhoneCode() == null ? 0 : this.getPhoneCode().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         
         
         return result;
   }   


}


