package org.mitre.openid.connect.sys.model;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name="SYS_M_PHONE"
)
public class Phone  implements java.io.Serializable {


     private Long idPhone;
     private PhoneType phoneType;
     private PhoneCode phoneCode;
     private String phonePrefix;
     private String phoneNo;
     private String phoneExt;
     private Date timeStart;
     private Date timeEnd;
     private Integer timeDurationMinute;
     private Integer seq;
     private String name;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<AddressMapPhone> addressMapPhones = new ArrayList<AddressMapPhone>(0);
     private List<UserMapPhone> userMapPhones = new ArrayList<UserMapPhone>(0);

    public Phone() {
    }

    public Phone(PhoneType phoneType, PhoneCode phoneCode, String phonePrefix, String phoneNo, String phoneExt, Date timeStart, Date timeEnd, Integer timeDurationMinute, Integer seq, String name, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<AddressMapPhone> addressMapPhones, List<UserMapPhone> userMapPhones) {
       this.phoneType = phoneType;
       this.phoneCode = phoneCode;
       this.phonePrefix = phonePrefix;
       this.phoneNo = phoneNo;
       this.phoneExt = phoneExt;
       this.timeStart = timeStart;
       this.timeEnd = timeEnd;
       this.timeDurationMinute = timeDurationMinute;
       this.seq = seq;
       this.name = name;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.addressMapPhones = addressMapPhones;
       this.userMapPhones = userMapPhones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PHONE", unique=true, nullable=false)
    public Long getIdPhone() {
        return this.idPhone;
    }
    
    public void setIdPhone(Long idPhone) {
        this.idPhone = idPhone;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PHONE_TYPE")
    public PhoneType getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(PhoneType phoneType) {
        this.phoneType = phoneType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PHONE_CODE")
    public PhoneCode getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(PhoneCode phoneCode) {
        this.phoneCode = phoneCode;
    }

    
    @Column(name="PHONE_PREFIX")
    public String getPhonePrefix() {
        return this.phonePrefix;
    }
    
    public void setPhonePrefix(String phonePrefix) {
        this.phonePrefix = phonePrefix;
    }

    
    @Column(name="PHONE_NO")
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    
    @Column(name="PHONE_EXT")
    public String getPhoneExt() {
        return this.phoneExt;
    }
    
    public void setPhoneExt(String phoneExt) {
        this.phoneExt = phoneExt;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="TIME_START", length=0)
    public Date getTimeStart() {
        return this.timeStart;
    }
    
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="TIME_END", length=0)
    public Date getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    
    @Column(name="TIME_DURATION_MINUTE")
    public Integer getTimeDurationMinute() {
        return this.timeDurationMinute;
    }
    
    public void setTimeDurationMinute(Integer timeDurationMinute) {
        this.timeDurationMinute = timeDurationMinute;
    }

    
    @Column(name="SEQ")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phone")
    public List<AddressMapPhone> getAddressMapPhones() {
        return this.addressMapPhones;
    }
    
    public void setAddressMapPhones(List<AddressMapPhone> addressMapPhones) {
        this.addressMapPhones = addressMapPhones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phone")
    public List<UserMapPhone> getUserMapPhones() {
        return this.userMapPhones;
    }
    
    public void setUserMapPhones(List<UserMapPhone> userMapPhones) {
        this.userMapPhones = userMapPhones;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idPhone").append("='").append(getIdPhone()).append("' ");			
      buffer.append("phoneType").append("='").append(getPhoneType()).append("' ");			
      buffer.append("phoneCode").append("='").append(getPhoneCode()).append("' ");			
      buffer.append("phonePrefix").append("='").append(getPhonePrefix()).append("' ");			
      buffer.append("phoneNo").append("='").append(getPhoneNo()).append("' ");			
      buffer.append("phoneExt").append("='").append(getPhoneExt()).append("' ");			
      buffer.append("timeStart").append("='").append(getTimeStart()).append("' ");			
      buffer.append("timeEnd").append("='").append(getTimeEnd()).append("' ");			
      buffer.append("timeDurationMinute").append("='").append(getTimeDurationMinute()).append("' ");			
      buffer.append("seq").append("='").append(getSeq()).append("' ");			
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Phone) ) return false;
		 Phone castOther = ( Phone ) other; 
         
		 return ( (this.getIdPhone()==castOther.getIdPhone()) || ( this.getIdPhone()!=null && castOther.getIdPhone()!=null && this.getIdPhone().equals(castOther.getIdPhone()) ) )
 && ( (this.getPhoneType()==castOther.getPhoneType()) || ( this.getPhoneType()!=null && castOther.getPhoneType()!=null && this.getPhoneType().equals(castOther.getPhoneType()) ) )
 && ( (this.getPhoneCode()==castOther.getPhoneCode()) || ( this.getPhoneCode()!=null && castOther.getPhoneCode()!=null && this.getPhoneCode().equals(castOther.getPhoneCode()) ) )
 && ( (this.getPhonePrefix()==castOther.getPhonePrefix()) || ( this.getPhonePrefix()!=null && castOther.getPhonePrefix()!=null && this.getPhonePrefix().equals(castOther.getPhonePrefix()) ) )
 && ( (this.getPhoneNo()==castOther.getPhoneNo()) || ( this.getPhoneNo()!=null && castOther.getPhoneNo()!=null && this.getPhoneNo().equals(castOther.getPhoneNo()) ) )
 && ( (this.getPhoneExt()==castOther.getPhoneExt()) || ( this.getPhoneExt()!=null && castOther.getPhoneExt()!=null && this.getPhoneExt().equals(castOther.getPhoneExt()) ) )
 && ( (this.getTimeStart()==castOther.getTimeStart()) || ( this.getTimeStart()!=null && castOther.getTimeStart()!=null && this.getTimeStart().equals(castOther.getTimeStart()) ) )
 && ( (this.getTimeEnd()==castOther.getTimeEnd()) || ( this.getTimeEnd()!=null && castOther.getTimeEnd()!=null && this.getTimeEnd().equals(castOther.getTimeEnd()) ) )
 && ( (this.getTimeDurationMinute()==castOther.getTimeDurationMinute()) || ( this.getTimeDurationMinute()!=null && castOther.getTimeDurationMinute()!=null && this.getTimeDurationMinute().equals(castOther.getTimeDurationMinute()) ) )
 && ( (this.getSeq()==castOther.getSeq()) || ( this.getSeq()!=null && castOther.getSeq()!=null && this.getSeq().equals(castOther.getSeq()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPhone() == null ? 0 : this.getIdPhone().hashCode() );
         result = 37 * result + ( getPhoneType() == null ? 0 : this.getPhoneType().hashCode() );
         result = 37 * result + ( getPhoneCode() == null ? 0 : this.getPhoneCode().hashCode() );
         result = 37 * result + ( getPhonePrefix() == null ? 0 : this.getPhonePrefix().hashCode() );
         result = 37 * result + ( getPhoneNo() == null ? 0 : this.getPhoneNo().hashCode() );
         result = 37 * result + ( getPhoneExt() == null ? 0 : this.getPhoneExt().hashCode() );
         result = 37 * result + ( getTimeStart() == null ? 0 : this.getTimeStart().hashCode() );
         result = 37 * result + ( getTimeEnd() == null ? 0 : this.getTimeEnd().hashCode() );
         result = 37 * result + ( getTimeDurationMinute() == null ? 0 : this.getTimeDurationMinute().hashCode() );
         result = 37 * result + ( getSeq() == null ? 0 : this.getSeq().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         
         
         return result;
   }   


}


