package org.mitre.openid.connect.sys.model;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProvinceId generated by hbm2java
 */
@Embeddable
public class ProvinceId  implements java.io.Serializable {


     private Long idProvince;
     private Long idCountry;

    public ProvinceId() {
    }

    public ProvinceId(Long idProvince, Long idCountry) {
       this.idProvince = idProvince;
       this.idCountry = idCountry;
    }
   


    @Column(name="ID_PROVINCE", nullable=false)
    public Long getIdProvince() {
        return this.idProvince;
    }
    
    public void setIdProvince(Long idProvince) {
        this.idProvince = idProvince;
    }


    @Column(name="ID_COUNTRY", nullable=false)
    public Long getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(Long idCountry) {
        this.idCountry = idCountry;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProvinceId) ) return false;
		 ProvinceId castOther = ( ProvinceId ) other; 
         
		 return ( (this.getIdProvince()==castOther.getIdProvince()) || ( this.getIdProvince()!=null && castOther.getIdProvince()!=null && this.getIdProvince().equals(castOther.getIdProvince()) ) )
 && ( (this.getIdCountry()==castOther.getIdCountry()) || ( this.getIdCountry()!=null && castOther.getIdCountry()!=null && this.getIdCountry().equals(castOther.getIdCountry()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdProvince() == null ? 0 : this.getIdProvince().hashCode() );
         result = 37 * result + ( getIdCountry() == null ? 0 : this.getIdCountry().hashCode() );
         return result;
   }   


}


