package org.mitre.openid.connect.sys.model;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * SocialNetworkType generated by hbm2java
 */
@Entity
@Table(name="SYS_M_SOCIAL_NETWORK_TYPE"
)
public class SocialNetworkType  implements java.io.Serializable {


     private Long idSocialNetworkType;
     private Integer seq;
     private String name;
     private String imageLogoPath;
     private String tip;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<SocialNetwork> socialNetworks = new ArrayList<SocialNetwork>(0);

    public SocialNetworkType() {
    }

    public SocialNetworkType(Integer seq, String name, String imageLogoPath, String tip, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<SocialNetwork> socialNetworks) {
       this.seq = seq;
       this.name = name;
       this.imageLogoPath = imageLogoPath;
       this.tip = tip;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.socialNetworks = socialNetworks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_SOCIAL_NETWORK_TYPE", unique=true, nullable=false)
    public Long getIdSocialNetworkType() {
        return this.idSocialNetworkType;
    }
    
    public void setIdSocialNetworkType(Long idSocialNetworkType) {
        this.idSocialNetworkType = idSocialNetworkType;
    }

    
    @Column(name="SEQ")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="IMAGE_LOGO_PATH")
    public String getImageLogoPath() {
        return this.imageLogoPath;
    }
    
    public void setImageLogoPath(String imageLogoPath) {
        this.imageLogoPath = imageLogoPath;
    }

    
    @Column(name="TIP")
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Basic
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="socialNetworkType")
    public List<SocialNetwork> getSocialNetworks() {
        return this.socialNetworks;
    }
    
    public void setSocialNetworks(List<SocialNetwork> socialNetworks) {
        this.socialNetworks = socialNetworks;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idSocialNetworkType").append("='").append(getIdSocialNetworkType()).append("' ");			
      buffer.append("seq").append("='").append(getSeq()).append("' ");			
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("imageLogoPath").append("='").append(getImageLogoPath()).append("' ");			
      buffer.append("tip").append("='").append(getTip()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SocialNetworkType) ) return false;
		 SocialNetworkType castOther = ( SocialNetworkType ) other; 
         
		 return ( (this.getIdSocialNetworkType()==castOther.getIdSocialNetworkType()) || ( this.getIdSocialNetworkType()!=null && castOther.getIdSocialNetworkType()!=null && this.getIdSocialNetworkType().equals(castOther.getIdSocialNetworkType()) ) )
 && ( (this.getSeq()==castOther.getSeq()) || ( this.getSeq()!=null && castOther.getSeq()!=null && this.getSeq().equals(castOther.getSeq()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getImageLogoPath()==castOther.getImageLogoPath()) || ( this.getImageLogoPath()!=null && castOther.getImageLogoPath()!=null && this.getImageLogoPath().equals(castOther.getImageLogoPath()) ) )
 && ( (this.getTip()==castOther.getTip()) || ( this.getTip()!=null && castOther.getTip()!=null && this.getTip().equals(castOther.getTip()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdSocialNetworkType() == null ? 0 : this.getIdSocialNetworkType().hashCode() );
         result = 37 * result + ( getSeq() == null ? 0 : this.getSeq().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getImageLogoPath() == null ? 0 : this.getImageLogoPath().hashCode() );
         result = 37 * result + ( getTip() == null ? 0 : this.getTip().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         
         return result;
   }   


}


